version: '0.1'
paths:
  specs: .specwright/specs
  aips: .specwright/aips
repo:
  default_branch: main
user:
  default_owner: benthepsychologist
  default_tier: C
current:
  spec: .specwright/specs/source-id-schema-update.md
  aip: /workspace/canonizer/.specwright/aips/source-id-schema-update.yaml
completed:
- spec: node-refactor.md
  aip: node-refactor.yaml
  completed_at: 2025-12-02 19:00:00+00:00
- spec: dataverse-and-stripe-schemas.md
  aip: dataverse-and-stripe-schemas.yaml
  completed_at: 2025-12-02 19:20:00+00:00
