version: '0.1'
paths:
  specs: .specwright/specs
  aips: .specwright/aips
repo:
  default_branch: main
user:
  default_owner: benthepsychologist
  default_tier: C
current:
  spec: null
  aip: null
completed:
  - spec: .specwright/specs/node-refactor.md
    aip: .specwright/aips/node-refactor.yaml
    completed_at: 2025-12-02T19:00:00+00:00
  - spec: .specwright/specs/dataverse-and-stripe-schemas.md
    aip: .specwright/aips/dataverse-and-stripe-schemas.yaml
    completed_at: 2025-12-02T19:20:00+00:00
