version: '0.1'
paths:
  specs: .specwright/specs
  aips: .specwright/aips
repo:
  default_branch: main
user:
  default_owner: benthepsychologist
  default_tier: C
current:
  spec: .specwright/specs/node-refactor.md
  aip: /workspace/canonizer/.specwright/aips/node-refactor.yaml
