version: '0.1'
paths:
  specs: .specwright/specs
  aips: .specwright/aips
repo:
  default_branch: main
user:
  default_owner: benthepsychologist
  default_tier: C
current:
  spec: .specwright/specs/canonizer-aip-v01-registry.md
  aip: /home/user/canonizer/.specwright/aips/canonizer-aip-v01-registry.yaml
